import type { ConfiguracaoHabilidade } from './habilidade.types';

export const habilidadesIniciais: ConfiguracaoHabilidade[] = [
  {
    nome: 'Combo Incandescente',
    descricao:
      'Após realizar 3 ataques, o próximo golpe substitui o ataque comum por um especial de 160%.',
    modoExecucao: 'AUTOMATICA',
    tipoEfeito: 'DANO',
    gatilho: 'AO_ATACAR',
    alvo: 'INIMIGO_ATIVO',
    unidade: 'PERCENTUAL',
    valorBase: 160,
    formaAplicacao: 'SUBSTITUI_ATAQUE',
    requisito: { tipo: 'CONTADOR_ATAQUES', quantidade: 3 },
    escala: { tipo: 'NENHUMA' },
    status: 'PUBLICADA',
  },
  {
    nome: 'Fúria Crescente',
    descricao:
      'Aumenta o ataque conforme a carta continua atacando, até o limite definido.',
    modoExecucao: 'AUTOMATICA',
    tipoEfeito: 'BUFF',
    gatilho: 'AO_ATACAR',
    alvo: 'PROPRIA_CARTA',
    atributo: 'ATAQUE',
    unidade: 'FIXO',
    valorBase: 6,
    formaAplicacao: 'APOS_ACAO',
    requisito: { tipo: 'NENHUM' },
    escala: { tipo: 'POR_ATAQUE', valor: 4, limite: 30 },
    duracaoTurnos: 2,
    status: 'PUBLICADA',
  },
  {
    nome: 'Barreira Instintiva',
    descricao:
      'Ao receber dano, cria um escudo temporário para proteger a própria carta.',
    modoExecucao: 'AUTOMATICA',
    tipoEfeito: 'ESCUDO',
    gatilho: 'AO_RECEBER_DANO',
    alvo: 'PROPRIA_CARTA',
    unidade: 'FIXO',
    valorBase: 35,
    formaAplicacao: 'APOS_ACAO',
    requisito: { tipo: 'NENHUM' },
    escala: { tipo: 'NENHUMA' },
    duracaoTurnos: 1,
    status: 'PUBLICADA',
  },
  {
    nome: 'Segundo Fôlego',
    descricao:
      'No início do turno, recupera 20% de vida quando a carta está abaixo de 35% do HP.',
    modoExecucao: 'AUTOMATICA',
    tipoEfeito: 'CURA',
    gatilho: 'INICIO_TURNO',
    alvo: 'PROPRIA_CARTA',
    unidade: 'PERCENTUAL',
    valorBase: 20,
    formaAplicacao: 'ANTES_ACAO',
    requisito: { tipo: 'HP_ABAIXO', percentual: 35 },
    escala: { tipo: 'NENHUMA' },
    status: 'PUBLICADA',
  },
  {
    nome: 'Presença Opressora',
    descricao:
      'Ao entrar em campo, reduz temporariamente a defesa da carta inimiga.',
    modoExecucao: 'AUTOMATICA',
    tipoEfeito: 'DEBUFF',
    gatilho: 'AO_ENTRAR',
    alvo: 'INIMIGO_ATIVO',
    atributo: 'DEFESA',
    unidade: 'PERCENTUAL',
    valorBase: 12,
    formaAplicacao: 'APOS_ACAO',
    requisito: { tipo: 'NENHUM' },
    escala: { tipo: 'NENHUMA' },
    duracaoTurnos: 3,
    status: 'PUBLICADA',
  },
  {
    nome: 'Colheita Sombria',
    descricao:
      'Ao atacar, converte 18% do dano causado em recuperação para a própria carta.',
    modoExecucao: 'AUTOMATICA',
    tipoEfeito: 'ROUBO_VIDA',
    gatilho: 'AO_ATACAR',
    alvo: 'PROPRIA_CARTA',
    unidade: 'PERCENTUAL',
    valorBase: 18,
    formaAplicacao: 'APOS_ACAO',
    requisito: { tipo: 'NENHUM' },
    escala: { tipo: 'NENHUMA' },
    status: 'PUBLICADA',
  },
];
